### ISSUE TITLE
有時候UI沒反應

### ISSUE THREAD

**Issue by saiwondMYsty** [KKGo1999/Stable-diffusion-person#1]
每次執行一次Generate後

UI 就會當掉

要嘛按了後跑圖跟UI兩個都沒反應，要嘛跑圖有再跑但UI沒反應

**Comment by KKGo1999** [comment]
你是用的哪个colab link遇到这个问题？尝试刷新下Web UI？

**Comment by jeferywblai** [comment]
我也是，生成完成一次就無法繼續生成圖片，使用stable_diffusion_webui_colab_chilloutmixni、stable_diffusion_webui_colab_chilloutmixni_koreandolllikeness_LoRA都是如此

**Comment by hokching** [comment]
The error occurs when "hi res fix" is clicked

"Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at index.98155427.js:76:2918
    at Array.forEach (<anonymous>)
    at st (index.98155427.js:76:2728)"

**Comment by hokching** [comment]
javascript error
