### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'

### ISSUE THREAD

**Issue by GunGunGun** [KKGo1999/Stable-diffusion-person#5]
```
Collecting fastapi==0.90.1
  Downloading fastapi-0.90.1-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.2/56.2 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /usr/local/lib/python3.10/dist-packages (from fastapi==0.90.1) (1.10.9)
Collecting starlette<0.24.0,>=0.22.0 (from fastapi==0.90.1)
  Downloading starlette-0.23.1-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 10.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi==0.90.1) (4.6.3)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.10/dist-packages (from starlette<0.24.0,>=0.22.0->fastapi==0.90.1) (3.7.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette<0.24.0,>=0.22.0->fastapi==0.90.1) (3.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette<0.24.0,>=0.22.0->fastapi==0.90.1) (1.3.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.4.0->starlette<0.24.0,>=0.22.0->fastapi==0.90.1) (1.1.1)
Installing collected packages: starlette, fastapi
Successfully installed fastapi-0.90.1 starlette-0.23.1
Cloning into 'stable-diffusion-webui'...
remote: Enumerating objects: 23147, done.
remote: Counting objects: 100% (255/255), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 23147 (delta 142), reused 188 (delta 113), pack-reused 22892
Receiving objects: 100% (23147/23147), 30.85 MiB | 22.76 MiB/s, done.
Resolving deltas: 100% (16096/16096), done.
Cloning into '/content/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 143 (delta 25), reused 21 (delta 21), pack-reused 109
Receiving objects: 100% (143/143), 37.96 KiB | 1.90 MiB/s, done.
Resolving deltas: 100% (51/51), done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1133  100  1133    0     0    980      0  0:00:01  0:00:01 --:--:--   980
100 4067M  100 4067M    0     0   196M      0  0:00:20  0:00:20 --:--:--  231M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1129  100  1129    0     0  14112      0 --:--:-- --:--:-- --:--:-- 13938
100 10155  100 10155    0     0  42136      0 --:--:-- --:--:-- --:--:-- 42136
/content/stable-diffusion-webui
Python 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai...
Cloning K-diffusion into /content/stable-diffusion-webui/repositories/k-diffusion...
Cloning CodeFormer into /content/stable-diffusion-webui/repositories/CodeFormer...
Cloning BLIP into /content/stable-diffusion-webui/repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements
Launching Web UI with arguments: --share --disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension-access
2023-07-11 07:42:09.641011: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-11 07:42:11.052269: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/stable-diffusion-webui/launch.py:38 in <module>                     │
│                                                                              │
│   35                                                                         │
│   36                                                                         │
│   37 if __name__ == "__main__":                                              │
│ ❱ 38 │   main()                                                              │
│   39                                                                         │
│                                                                              │
│ /content/stable-diffusion-webui/launch.py:34 in main                         │
│                                                                              │
│   31 │   if args.test_server:                                                │
│   32 │   │   configure_for_tests()                                           │
│   33 │                                                                       │
│ ❱ 34 │   start()                                                             │
│   35                                                                         │
│   36                                                                         │
│   37 if __name__ == "__main__":                                              │
│                                                                              │
│ /content/stable-diffusion-webui/modules/launch_utils.py:340 in start         │
│                                                                              │
│   337                                                                        │
│   338 def start():                                                           │
│   339 │   print(f"Launching {'API server' if '--nowebui' in sys.argv else 'W │
│ ❱ 340 │   import webui                                                       │
│   341 │   if '--nowebui' in sys.argv:                                        │
│   342 │   │   webui.api_only()                                               │
│   343 │   else:                                                              │
│                                                                              │
│ /content/stable-diffusion-webui/webui.py:42 in <module>                      │
│                                                                              │
│    39 startup_timer.record("import ldm")                                     │
│    40                                                                        │
│    41 from modules import extra_networks                                     │
│ ❱  42 from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, │
│    43                                                                        │
│    44 # Truncate version number of nightly/local build of PyTorch to not cau │
│    45 if ".dev" in torch.__version__ or "+git" in torch.__version__:         │
│                                                                              │
│ /content/stable-diffusion-webui/modules/call_queue.py:5 in <module>          │
│                                                                              │
│     2 import threading                                                       │
│     3 import time                                                            │
│     4                                                                        │
│ ❱   5 from modules import shared, progress, errors                           │
│     6                                                                        │
│     7 queue_lock = threading.Lock()                                          │
│     8                                                                        │
│                                                                              │
│ /content/stable-diffusion-webui/modules/shared.py:18 in <module>             │
│                                                                              │
│    15 import modules.devices as devices                                      │
│    16 from modules import localization, script_loading, errors, ui_component │
│    17 from modules.paths_internal import models_path, script_path, data_path │
│ ❱  18 from ldm.models.diffusion.ddpm import LatentDiffusion                  │
│    19 from typing import Optional                                            │
│    20                                                                        │
│    21 demo = None                                                            │
│                                                                              │
│ /content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/l │
│ dm/models/diffusion/ddpm.py:20 in <module>                                   │
│                                                                              │
│     17 import itertools                                                      │
│     18 from tqdm import tqdm                                                 │
│     19 from torchvision.utils import make_grid                               │
│ ❱   20 from pytorch_lightning.utilities.distributed import rank_zero_only    │
│     21 from omegaconf import ListConfig                                      │
│     22                                                                       │
│     23 from ldm.util import log_txt_as_img, exists, default, ismap, isimage, │
╰──────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
```

Any idea how doesn't this collab work anymore ? I'm running it from Google Collab.

**Comment by zhemeduogewangtianyi** [comment]
Launching Web UI with arguments: --share --disable-safe-unpickle --no-half-vae --xformers --reinstall-xformers --enable-insecure-extension-access
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/content/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/content/stable-diffusion-webui/modules/launch_utils.py", line 465, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/stable-diffusion-webui/modules/initialize.py", line 35, in imports
    from modules import shared_init
  File "/content/stable-diffusion-webui/modules/shared_init.py", line 5, in <module>
    from modules import shared
  File "/content/stable-diffusion-webui/modules/shared.py", line 6, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "/content/stable-diffusion-webui/modules/sd_models_types.py", line 1, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "/content/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 20, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
